server.port=${PORT:8080}
spring.application.name=eureka-server
management.endpoints.web.exposure.include=health,info
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
demo.timezone=America/Chicago
